### PR TITLE
Add composer.json for pickle.

### PR DESCRIPTION
**Pull request by shouze**
Fixes https://github.com/krakjoe/apcu-bc/issues/7

### CODE REVIEW

**Comment by krakjoe** [comment]
Thanks ;)

We will add pecl/pickle builds to CI ...

**Comment by shouze** [comment]
@krakjoe :+1:  pickle can't still automatically download apcu dependency and/or check it's already installed on the fly & install it but it's the future of the project.

**Comment by krakjoe** [comment]
@shouze I don't know anything about pickle at the moment ... will familiarize myself ...

**Comment by pierrejoye** [comment]
I would recommend to remove the version in composer.json

pickle will use the version available in the header and makes sure it matches the tag. Doing so finally let the developer focus only on one location instead of having to update many different locations.

You do not have to do it tho', it could simply ease your work.

**Comment by shouze** [comment]
@pierrejoye ok, fixed in https://github.com/krakjoe/apcu-bc/pull/11

**Comment by pierrejoye** [comment]
About role and other meta, it i the exact same format used by composer. So the composer references apply here.

We may add some custom extra fields if necessary, mainly to deal with system deps. But that remains fully compatible (and parse-able) by composer.

**Pull request merged**
